version: '3.7'
services:
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:7.6.2
    privileged: true
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_HEAP_SIZE=2G
      - TZ=Europe/Istanbul
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "elasticdata:/usr/share/elasticsearch/data"

  kibana:
    image: kibana:7.6.2
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "80:5601"
    depends_on:
      - elasticsearch

  logstash:
    hostname: logstash
    image: logstash:7.6.2
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash.yml:/etc/logstash/conf.d/logstash.yml
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xmx1024m -Xms1024m
      - TZ=Europe/Istanbul

volumes:
  elasticdata:
